apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  namespace: junan-namespace  # 네임스페이스 지정시, 여기에 지정
  labels:
    app: my-nginx
spec:
  containers:
    - name: my-nginx
      image: nginx
      ports:
      - containerPort: 80