apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: junan-namespace
  # labels는 서비스의 라우팅 대상이 되는 이름
  # service의 selector.app을 통해 매핑
spec:
  type: NodePort
  ports:
  - port: 80 #서비스의 포트
    targetPort: 80 #pod의 포트
    nodePort: 30081 #ec2의 포트
  selector:
    app: my-nginx